# Lane detection parameters
processing:
  use_every_Xth_frame: 5  # Process every nth frame
  use_every_Xth_frame_2: 11
  crop_height_percentage: 0.375  # Crop 37.5% from the top
  roi_height: 145  # Height for lane center extraction (px from top)
  roi_height_proximity: 220
  
# Default values for lane detection fallback
defaults:
  center_white: 600  # Relative position (percentage of image width)
  center_yellow: 40  # Relative position (percentage of image width)
  center_dotted: 300  # Relative position (percentage of image width)

# Proximity to intersection parameters
intersection_proximity:
  window_height: 240
  window_width: 200
  window_bottom_offset: 0

# Red stop detection parameters
red_stop:
  window_height: 100  # Height of the window (px)
  window_width: 350  # Width of the window (px)
  window_bottom_offset: 0  # Offset from bottom (px)
  detection_threshold: 35  # Percentage threshold for stop detection

# CenterCheckDuckie
center_check_duckie:
  target_class_id: 1
  region:
    x_min: 100
    y_min: 50
    x_max: 450
    y_max: 300

# RichtCheckDuckie
right_check_duckie:
  target_class_id: 1
  region:
    x_min: 450
    y_min: 0
    x_max: 640
    y_max: 480

# RichtCheckDuckie
parking:
  bot_class_id: 0
  duckie_class_id: 1
  target_class_id: 2
  region:
    x_min: 400
    y_min: 0
    x_max: 640
    y_max: 480

# TrafficRulesDuckie
traffic_rules_duckie:
  target_class_id: 0
  region_right:
    x_min: 400
    y_min: 0
    x_max: 640
    y_max: 280
  region_front:
    x_min: 0
    y_min: 0
    x_max: 250
    y_max: 220