# Lane detection parameters
processing:
  use_every_Xth_frame: 6  # Process every nth frame
  use_every_Xth_frame_2: 1000
  crop_height_percentage: 0.375  # Crop 37.5% from the top
  roi_height: 100  # Height for lane center extraction (px from top)
  
# Default values for lane detection fallback
defaults:
  center_white: 600  # Relative position (percentage of image width)
  center_yellow: 40  # Relative position (percentage of image width)
  center_dotted: 300  # Relative position (percentage of image width)


# Red stop detection parameters
red_stop:
  window_height: 80  # Height of the window (px)
  window_width: 640  # Width of the window (px)
  window_bottom_offset: 0  # Offset from bottom (px)
  detection_threshold: 50  # Percentage threshold for stop detection